#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
# AEM configuration for local development environment

nodes:

- node: aem-author
  roles:
  - role: ${projectName}-aem-cms
    variant: aem-author
  config:
    replication.author.publishTargets:
    - name: publish
      url: ${symbol_dollar}{maven::sling.publish.url}
      transportUser: admin
      transportPassword: admin

- node: aem-publish
  roles:
  - role: ${projectName}-aem-cms
    variant: aem-publish


config:
  contentPackage.group: ${packageGroupName}
  app:
    # Default log level for application code
    logLevel: info
#if ( $optionContextAwareConfig == "y" || $optionEditableTemplates == "y" )
    # Whether to deploy conf content with editable template definitions
    confContent: true
#end
    # Whether to deploy sample content
    sampleContent: true

  quickstart:
    # Enable Apache Sling DavEx Servlet to be able to use CRXDE Lite
    enableDavEx: true
#if ($optionAemVersion == "cloud")

  # Not used for AEM cloud
  cloudManager.target:
  - none
#end
